name: Matrix

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6,8,12]
      max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - name: Change Node Version
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: node -v